### ISSUE TITLE
Crash on handling push event

### ISSUE THREAD

**Issue by n1rvana** [lmars/flynn-webhook-deploy#4]
```

2016-01-20T21:59:36.149485Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: 2016/01/20 21:59:36 handling request
2016-01-20T21:59:36.149888Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: 2016/01/20 21:59:36 received push event
2016-01-20T21:59:36.150961Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: 2016/01/20 21:59:36 http: panic serving 100.100.69.1:48401: runtime error: invalid memory address or nil pointer dereference
2016-01-20T21:59:36.151016Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: goroutine 3113 [running]:
2016-01-20T21:59:36.151168Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: net/http.func·011()
2016-01-20T21:59:36.151329Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /usr/local/go/src/net/http/server.go:1130 +0xbb
2016-01-20T21:59:36.151358Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/flynn/go-sql.(*DB).conn(0x0, 0x1, 0x0, 0x0)
2016-01-20T21:59:36.151490Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /tmp/build/.heroku/go/src/github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/flynn/go-sql/sql.go:662 +0x811
2016-01-20T21:59:36.151647Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/flynn/go-sql.(*DB).query(0x0, 0x867830, 0x53, 0xc2080d3920, 0x2, 0x2, 0x7f0d4a1b70a8, 0x0, 0x0)
2016-01-20T21:59:36.151738Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /tmp/build/.heroku/go/src/github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/flynn/go-sql/sql.go:967 +0x43
2016-01-20T21:59:36.151903Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/flynn/go-sql.(*DB).Query(0x0, 0x867830, 0x53, 0xc2080d3920, 0x2, 0x2, 0x41005c, 0x0, 0x0)
2016-01-20T21:59:36.152050Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /tmp/build/.heroku/go/src/github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/flynn/go-sql/sql.go:958 +0xa6
2016-01-20T21:59:36.152230Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/flynn/go-sql.(*DB).QueryRow(0x0, 0x867830, 0x53, 0xc2080d3920, 0x2, 0x2, 0x458160)
2016-01-20T21:59:36.152425Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /tmp/build/.heroku/go/src/github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/flynn/go-sql/sql.go:1036 +0x66
2016-01-20T21:59:36.152592Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: main.getRepo(0xc2080e2e40, 0x1a, 0xc2080e288b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016-01-20T21:59:36.152753Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /tmp/build/.heroku/go/src/github.com/lmars/flynn-webhook-deploy/webhook.go:164 +0x1bf
2016-01-20T21:59:36.152808Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: main.webhook(0x7f0d4a1c6cf0, 0xc20803caa0, 0xc20803e820, 0x0, 0x0, 0x0)
2016-01-20T21:59:36.152938Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /tmp/build/.heroku/go/src/github.com/lmars/flynn-webhook-deploy/webhook.go:223 +0xb8c
2016-01-20T21:59:36.153125Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc20803bdd0, 0x7f0d4a1c6cf0, 0xc20803caa0, 0xc20803e820)
2016-01-20T21:59:36.153150Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /tmp/build/.heroku/go/src/github.com/lmars/flynn-webhook-deploy/Godeps/_workspace/src/github.com/julienschmidt/httprouter/router.go:299 +0x18e
2016-01-20T21:59:36.153366Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: net/http.serverHandler.ServeHTTP(0xc20805ade0, 0x7f0d4a1c6cf0, 0xc20803caa0, 0xc20803e820)
2016-01-20T21:59:36.153527Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /usr/local/go/src/net/http/server.go:1703 +0x19a
2016-01-20T21:59:36.153610Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: net/http.(*conn).serve(0xc20803ca00)
2016-01-20T21:59:36.153808Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /usr/local/go/src/net/http/server.go:1204 +0xb57
2016-01-20T21:59:36.153975Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]: created by net/http.(*Server).Serve
2016-01-20T21:59:36.154003Z app[web.flynn1453239883vm2-6cec5200-039f-49c1-adcd-97a6ef11bded]:   /usr/local/go/src/net/http/server.go:1751 +0x35e

```

**Comment by lmars** [comment]
Fixed in https://github.com/lmars/flynn-webhook-deploy/commit/6cf7e9f234f9ac2be84c3c46ec65fa7cbac7bce8
